I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/monica.rpy", line 24, in script
    scene hotel outside with fade
Exception: Image 'hotel' does not accept attributes 'outside'.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/monica.rpy", line 24, in script
    scene hotel outside with fade
  File "/Applications/renpy-7.4.6-sdk/renpy/ast.py", line 1542, in execute
    show_imspec(self.imspec, atl=getattr(self, "atl", None))
  File "/Applications/renpy-7.4.6-sdk/renpy/ast.py", line 1371, in show_imspec
    renpy.config.show(name,
  File "/Applications/renpy-7.4.6-sdk/renpy/exports.py", line 686, in show
    if not base.find_target() and renpy.config.missing_show:
  File "/Applications/renpy-7.4.6-sdk/renpy/display/image.py", line 413, in find_target
    self.target = target._duplicate(a)
  File "/Applications/renpy-7.4.6-sdk/renpy/display/core.py", line 397, in _duplicate
    args.extraneous()
  File "/Applications/renpy-7.4.6-sdk/renpy/display/core.py", line 265, in extraneous
    raise Exception("Image '{}' does not accept attributes '{}'.".format(
Exception: Image 'hotel' does not accept attributes 'outside'.

macOS-10.16-x86_64-i386-64bit x86_64
Ren'Py 8.0.1.22070503n
Holidays in Harkmall 1.0
Wed Dec 14 16:42:33 2022
